name: xarraytest_lh
channels:
  - conda-forge
  - defaults
dependencies:
   # Required for full project functionality (dont remove)
  - pytest
  # Other (remove and add as needed)
  - jupyter
  - jupyterlab
  - xarray==0.15.1
  - numpy==1.18.1
  - scipy
  - netcdf4
  - pandas==1.0.3
  - matplotlib
