name: xarraytest_lh
channels:
  - conda-forge
  - defaults
dependencies:
   # Required for full project functionality (dont remove)
  - pytest
  # Other (remove and add as needed)
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - scipy
  - netcdf4
  - pandas
  - matplotlib